# Docker Compose for development with the UC Core Simulator
name: integration-stormaudio

services:
  # Unfolded Circle Core Simulator for testing
  core-simulator:
    image: unfoldedcircle/core-simulator:latest
    restart: "unless-stopped"
    hostname: core-simulator
    environment:
      - UC_INTEGRATION_DISABLE_CERT_VERIFICATION=true
    ports:
      - "8080:8080"
      - "8443:8443"
    volumes:
      - simulator-data:/data
    depends_on:
      - uc-intg-stormaudio

  # Your integration service
  uc-intg-stormaudio:
     build:
       dockerfile: ./Dockerfile
     hostname: uc-intg-stormaudio
     environment:
       - UC_DISABLE_MDNS_PUBLISH=false
       - UC_MDNS_LOCAL_HOSTNAME=
       - UC_INTEGRATION_INTERFACE=0.0.0.0
       - UC_INTEGRATION_HTTP_PORT=9090
     volumes:
       - integration-data:/config
     develop:
       watch:
         - path: ./requirements.txt
           action: rebuild

         - path: uc_intg_stormaudio
           target: /app/uc_intg_stormaudio
           action: sync+restart

         - path: ./driver.json
           target: /app/driver.json
           action: sync+restart
     depends_on:
       - echo-server

  echo-server:
     build:
       dockerfile: ./server.Dockerfile
     hostname: echo-server
     ports:
       - 23:23
     develop:
       watch:
         - path: ./requirements.txt
           action: rebuild

         - path: ./server.py
           target: /app/server.py
           action: sync+restart

volumes:
  simulator-data:
  integration-data:
