name: release
on:
  push:
    branches:
      - main

concurrency:
  group: release-please

permissions:
  contents: write
  issues: write
  pull-requests: write

env:
  INTG_NAME: stormaudio

jobs:
  release-please:
    runs-on: ubuntu-24.04-arm
    defaults:
      run:
        shell: bash
    steps:
      - uses: googleapis/release-please-action@v5
        id: release
        with:
          token: ${{ secrets.GOOGLE_RELEASE_PLEASE_TOKEN }}
          # @see https://github.com/googleapis/release-please/blob/main/docs/manifest-releaser.md#configfile
          config-file: 'release-please-config.json'
          manifest-file: .release-please-manifest.json

      - name: Checkout
        if: ${{ steps.release.outputs.release_created }}
        uses: actions/checkout@v7

      - name: Install Python
        if: ${{ steps.release.outputs.release_created }}
        uses: actions/setup-python@v7

      - name: Install UV
        if: ${{ steps.release.outputs.release_created }}
        uses: astral-sh/setup-uv@v10.0.0

      - name: Install the dependencies
        if: ${{ steps.release.outputs.release_created }}
        run: uv sync

      - name: Get version and id
        if: ${{ steps.release.outputs.release_created }}
        run: |
          echo "DRIVER_ID=$(jq .driver_id -r driver.json)" >> $GITHUB_ENV

      - name: Build
        if: ${{ steps.release.outputs.release_created }}
        run: pyinstaller --clean --onedir --name intg-${{ env.DRIVER_ID }} --collect-all zeroconf uc_intg_${{ env.INTG_NAME }}/__main__.py

      - name: Prepare artifacts
        if: ${{ steps.release.outputs.release_created }}
        shell: bash
        run: |
          mkdir -p artifacts/bin
          mv dist/intg-${{ env.DRIVER_ID }}/* artifacts/bin
          mv artifacts/bin/intg-${{ env.DRIVER_ID }} artifacts/bin/driver
          cp driver.json artifacts/
          echo "ARTIFACT_NAME=uc-intg-${{ env.DRIVER_ID }}-${{ steps.release.outputs.tag_name }}-aarch64" >> $GITHUB_ENV

      - name: Create upload artifact archive
        if: ${{ steps.release.outputs.release_created }}
        shell: bash
        run: | 
          tar czvf ${{ env.ARTIFACT_NAME }}.tar.gz -C ${GITHUB_WORKSPACE}/artifacts .

      - name: Upload Release Artifact
        if: ${{ steps.release.outputs.release_created }}
        env:
          GITHUB_TOKEN: ${{ secrets.GOOGLE_RELEASE_PLEASE_TOKEN }}
        run:
          gh release upload ${{ steps.release.outputs.tag_name }} ${{ env.ARTIFACT_NAME }}.tar.gz

      - name: Publish Immutable Release
        if: ${{ steps.release.outputs.release_created }}
        run: gh release edit "${{ steps.release.outputs.tag_name }}" --draft=false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}